### ISSUE TITLE
OdbcFb.dll: load of FbClient.dll from local dir [ODBC126]

### ISSUE THREAD

**Issue by firebird-automations** [mrotteveel/firebird-odbc-driver#123]
Submitted by: ohenri (ohenri)

Actually, it seems that OdbcFb\.dll itself will be loaded according the spec in the registry 
\(HKLM\\Software\\ODBC\\ODBCINST\.INI\\Firebird/InterBase\(r\) driver\\Driver = Path of the OdbcFb dll\.

Then, OdbcFb dll seems to load the Gds32/Fbclient more or less directly from the \\System32 directory\.

Problem: 
It is not possible to run ODBC with explicit different firebird client versions kept in well defined different directories\.

Request:
The OdbcFb\.dll shall try to load the FB\-Client library \(fbclient or gds32\) by following sequences:

1\. Try to load from the current directory
2\. Try to load from the directory where OdbcFb\.dll is found
3\. Try to load by default search pathes of the system \(which points then, usually, to System32\)

2\) is the requested new feature\.

**Comment by MicheleFire2022** [comment]
Hi Guys, can i have the ODBC patched for ms access? i can't find the attach to this tread

Thanks a lot
Br
