### ISSUE TITLE
"Reserved error (-7748); there is no message for this error" with MS Access on UTF8 DBs [ODBC156]

### ISSUE THREAD

**Issue by firebird-automations** [mrotteveel/firebird-odbc-driver#151]
Submitted by: Bjoern Reimer (bnreimer)

Attachments:
[odbc-156.sql](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-156/12270_odbc-156.sql)
[DBUTF8.ZIP](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-156/12271_DBUTF8.ZIP)
[OdbcFb.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-156/12272_OdbcFb.zip)

\-  Install InterBase ODBC driver 
\- Install Firebird Client Only
\- Create an ODBC DataSource to the attached UTF8 character set Firebird database file using 32 Bit the "ODBC Data Source Adminstrator" tool\. 
\- Start Microsoft Access 2003 or 2010
\- Create a blank new access database
\- Click on "External Data" tab and select "More" dropdown, "ODBC Database"
\- In the wizard, select "Machine Data Source" \(or User Data Source \- depends on config\) tab, and pick your ODBC data source
\- Select any table \(I selected TLATIN2\) from the list of tables presented, and press OK

You are presented with an "Microsoft Office Access" error, and the data is not imported:
"Reserved error \(\-7748\); there is no message for this error\."

Commits: FirebirdSQL/firebird-odbc-driver@560362fdec70dd5f544b1e26c8080db3ab90a958 FirebirdSQL/firebird-odbc-driver@8702c49c768de5898fccdf63b902c99dd5a6c19c

**Comment by DanCypress** [comment]
I too an facing the same problem. Any [solution](https://chicagopopcornceilingremoval.com)?
